### ISSUE TITLE
EFI Image not working Monterey version

### ISSUE THREAD

**Issue by xsario** [mmatongo/HP-450G5-Hackintosh#1]
Hi, my friend. I used your EFI file and this efi does not boot my HP 450 G5 i5 laptop. I changed smbios entry but not booting yet. I got this all the time this error.
https://ibb.co/w7pQj9N
 
And my EFI file is here. 
https://we.tl/t-8SE3Vc18cm

Could you please help me with this? Thank you.

**Comment by mmatongo** [comment]
Hey, I am using this EFI on macOS Monterey 12.1.

I get that error as well but it always passes that point
![Screenshot 2022-02-09 at 2 09 39 PM](https://user-images.githubusercontent.com/40806126/153198445-72058715-885c-43ab-be4a-7747f4e74b81.png)


I will take a look at your EFI soon.

**Comment by mmatongo** [comment]
Hey, I am using this EFI on macOS Monterey 12.1.

I get that error as well but it always passes that point
![Screenshot 2022-02-09 at 2 09 39 PM](https://user-images.githubusercontent.com/40806126/153198445-72058715-885c-43ab-be4a-7747f4e74b81.png)


I will take a look at your EFI soon.

**Comment by xsario** [comment]
Thank you for your fast reply. I tested Monterey 12.0,12.1,12.2 images and I got same error :( .
What is the bios version of your laptop so that I can compare it with my laptop?
My bios version is : 01.14.01

**Comment by mmatongo** [comment]
Same version

**Comment by mmatongo** [comment]
Remove this [ApplePS2SmartTouchPad.kext](https://github.com/mmatongo/HP-450G5-Hackintosh/tree/master/EFI/OC/Kexts/ApplePS2SmartTouchPad.kext)

**Comment by xsario** [comment]
Hello, my Friend. I created a new EFI using the Opencore KabyLake template. I installed Monterey 12.2 without any problems with the EFI I prepared. I've shared it on my GitHub repo if you want to try it.
Thank you for all your help.
https://github.com/xsario/HP-ProBook-450G5-i5-Hackintosh
